[mypy]
python_version = 3.10
strict = False
disable_error_code = import-untyped,import-not-found
# TODO: consider enabling the following once
# all optional values are explicitly specified.
no_implicit_optional = False
