[metadata]
name = openvixdisklib
summary =
    A reverse engineered replacement for the proprietary VMware VDDK vixdisklib
    library.
description-file = README.md
author = Cloudbase Solutions SRL
author-email = info@cloudbasesolutions.com
home-page = http://cloudbase.it
classifier =
    Environment :: VMware
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.12

[files]
packages =
    openvixdisklib

[global]
setup-hooks =
    pbr.hooks.setup_hook

[wheel]
universal = 1
